### ISSUE TITLE
how can i inference on my custom football video that i have download from youtbe

### ISSUE THREAD

**Issue by Shekharmeena28** [lRomul/ball-action-spotting#2]
there is no steps how can i inference on the custom video and detect the action on top of it, can u please help me?

**Comment by lRomul** [comment]
You can write a custom inference script using the [get_raw_predictions](https://github.com/lRomul/ball-action-spotting/blob/9c471531c62b51bd0cfe6170b74d035da44c88ed/scripts/ball_action/predict.py#L29) function. To get predictions, you should pass the [created predictor](https://github.com/lRomul/ball-action-spotting/blob/9c471531c62b51bd0cfe6170b74d035da44c88ed/scripts/ball_action/predict.py#L115) and the video path to the function. Model weights can be downloaded [here](https://github.com/lRomul/ball-action-spotting#trained-models).

**Comment by lcc157** [comment]
> there is no steps how can i inference on the custom video and detect the action on top of it, can u please help me?

Have you achieved it ？

**Comment by Tortoise17** [comment]
@lRomul is there any update or help in this?
